[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
dependsOn = ["setup"]
cmds = ["dotnet restore"]

[phases.build]
dependsOn = ["install"]
cmds = ["dotnet publish TokoApi.csproj -c Release -o out --no-self-contained"]